# Generated by Django 4.2.7 on 2023-11-17 21:44

import blog_app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0002_imagemodel_picname_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=blog_app1.models.upload_to),
        ),
    ]
